### ISSUE TITLE
[URGENT] The link in the project description is a NSFW website

### ISSUE THREAD

**Issue by anjannair** [MicroPyramid/react-radio-player#2]
Maintainers please take note that the link in the description of this project is an **adult website** (probably with the same name as your project or the site was overtaken by nefarious actors) with popups which lead to dangerous links which could contain malware.

The website should be taken down and fixed immediately if it is the correct link to the project otherwise users visiting this project will have a negative experience.
I will be sending a mail regarding the same if this issue isn't resolved immediately.

**Comment by ashwin31** [comment]
Thank you, I removed it.

**Comment by anjannair** [comment]
Great!

**Comment by ashwin31** [comment]
We will host on a new site with updated UI
